[project]
name = "bookapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "granian>=2.7.0",
    "litestar>=2.19.0",
    "piccolo[all]>=1.30.0",
    "ruff>=0.15.0",
]
